version: '3'

services:
  app:
    build:
      context: ./front-end
      args:
        BUILD_PROFILE: dev
    environment:
      API_URL: http://api
    ports:
      - '8080:80'
    depends_on:
      - api
  api:
    build:
      context: highscore-api/HighScoreApi
      args:
        CRON_CLEANUP_SCHEDULE: '0 * * * * *'
    environment:
      CONNECTION_STRING: mongodb://root:secret@db
    ports:
      - '8081:80'
    depends_on:
      - db
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    expose:
      - '27017'
    volumes:
      - snake-db:/data/db

volumes:
  snake-db:
