version: '3'

services:
  app:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    image: ghcr.io/christianfosli/snake/wasm-app
    environment:
      API_URL: http://api:3000
    ports:
      - '8080:80'
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: highscore-api/Dockerfile
    image: ghcr.io/christianfosli/snake/highscore-api
    environment:
      DB_CONNSTR: mongodb://root:secret@db
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
  cleanup-job:
    build:
      context: .
      dockerfile: highscore-cleanup-job/Dockerfile
    image: ghcr.io/christianfosli/snake/highscore-cleanup-job
    environment:
      DB_CONNSTR: mongodb://root:secret@db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    expose:
      - '27017'
    volumes:
      - snake-db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

volumes:
  snake-db:
