version: '3'

services:
  app:
    build:
      context: .
      dockerfile: front-end/Dockerfile
      args:
        BUILD_PROFILE: dev
    environment:
      API_URL: http://api:3000
    ports:
      - '8080:80'
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: highscore-api/Dockerfile
      args:
        CARGO_INSTALL_OPTIONS: --debug
    environment:
      DB_CONNSTR: mongodb://root:secret@db
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    expose:
      - '27017'
    volumes:
      - snake-db:/data/db

volumes:
  snake-db:
