version: '3'

services:
  app:
    build:
      context: ./front-end
      args:
        BUILD_PROFILE: dev
        HIGHSCORE_API_BASE_URL: http://localhost:7071
    ports:
      - '8080:8080'
  api:
    build:
      context: highscore-api/HighScoreApi
      args:
        CRON_CLEANUP_SCHEDULE: '0 * * * * *'
    environment:
      CONNECTION_STRING: mongodb://root:secret@db
    ports:
      - '7071:80'
    depends_on:
      - db
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'
    volumes:
      - snake-db:/data/db

volumes:
  snake-db:
