version: '3'

services:
  app:
    build: front-end
    ports:
      - '1234:1234'
    volumes:
      - './front-end/src:/usr/src/app/src'
  api:
    build: highscore-api
    ports:
      - '7071:80'
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=Secret_01
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'
    volumes:
      - 'sql-server-data:/var/opt/mssql'

volumes:
  sql-server-data:
