version: '3'

services:
  app:
    build:
      context: ./front-end
      args:
        BUILD_PROFILE: dev
        HIGHSCORE_API_BASE_URL: http://localhost:7071
    ports:
      - '8080:8080'
  api:
    build:
      context: highscore-api/HighScoreApi
      args:
        CRON_CLEANUP_SCHEDULE: '0 * * * * *'
    environment:
      - CONNECTION_STRING=Server=tcp:db,1433;Database=snake-hs;User ID=sa;Password=Secret_01
    ports:
      - '7071:80'
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=Secret_01
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'
    volumes:
      - './database/entrypoint.bash:/entrypoint.bash'
      - './database/init.bash:/init.bash'
      - './database/schema.sql:/schema.sql'
    command: /bin/bash /entrypoint.bash

