version: '3'

services:
  app:
    build: front-end
    ports:
      - '1234:1234'
    volumes:
      - './front-end/src:/usr/src/app/src'
      - './front-end/index.html:/usr/src/app/index.html'
      - './front-end/style.css:/usr/src/app/style.css'
  api:
    build: highscore-api
    environment:
      - CONNECTION_STRING=Server=tcp:db,1433;Database=snake-hs;User ID=sa;Password=Secret_01
    ports:
      - '7071:80'
    depends_on:
      - db
  api-fs:
    build:
      context: highscore-api-fs
      args:
        CRON_CLEANUP_SCHEDULE: '*/30 * * * * *'
    environment:
      - CONNECTION_STRING=Server=tcp:db,1433;Database=snake-hs;User ID=sa;Password=Secret_01
    ports:
      - '7072:80'
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=Secret_01
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'
    volumes:
      - './database/entrypoint.bash:/entrypoint.bash'
      - './database/init.bash:/init.bash'
      - './database/schema.sql:/schema.sql'
    command: /bin/bash /entrypoint.bash

