[package]
name = "visnake"
authors = ["Christian Fosli <cfosli@gmail.com>"]
categories = ["wasm"]
license = "MIT"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen-futures = "0.4"
gloo-timers = "0.2"
gloo-events = "0.1"
futures = "0.3"
serde_derive = "1.0"

[dependencies.serde]
version = "1.0"
features = [
  "derive",
]

[dependencies.wasm-bindgen]
version = "0.2"
features = [
  "serde-serialize",
]

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "CanvasRenderingContext2d",
  "Document",
  "Element",
  "Headers",
  "HtmlElement",
  "HtmlCanvasElement",
  "KeyboardEvent",
  "Node",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
]

[dependencies.rand]
version = "0.7"
features = [
  "wasm-bindgen",
]

[dev-dependencies]
wasm-bindgen-test = "0.3"
js-sys = "0.3"
