name: az-functions-deploy

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'
      - run: |
          cd highscore-api
          dotnet build --configuration Release --output ./output
      - uses: azure/login@v1
      - uses: azure/functions-action@v1
        with:
          app-name: visnakehighscores
          package: highscore-api/output
