name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Change directory
        run: cd crate
      
      - name: Cargo test
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.5
    - uses: actions/setup-node@v1.1.0
      with:
        version: lts
    - uses: jetli/wasm-pack-action@v0.2.0

    - name: Install javascript dependencies
      run: npm install
    
    - name: Build
      run: npm run build
