name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cargo test
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          args: --manifest-path=crate/Cargo.toml

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.5
      with:
        toolchain: stable
    - uses: actions/setup-node@v1.1.0
      with:
        version: 12.x
    - uses: jetli/wasm-pack-action@v0.2.0

    - name: Install javascript dependencies
      run: npm install
    
    - name: Build
      run: npm run build

    - name: TODO Upload to azure storage
      if: ${{ github.event_name }} == 'push'
      run: printf "Should upload to cloud storage\n"
