name: wasm_app

on:
  push:
    branches: [master]
    paths:
      - front-end/**
      - .github/workflows/wasm_app.yml
  pull_request:
    branches: [master]
    paths:
      - front-end/**
      - .github/workflows/wasm_app.yml

defaults:
  run:
    working-directory: front-end

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Cargo test
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          toolchain: stable
          args: --manifest-path front-end/Cargo.toml

      - name: Wasm test
        run: wasm-pack test --headless --chrome

  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build --build-arg BUILD_PROFILE=dev .

  build-and-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Copy Artifacts
        run: |
          docker build \
            --build-arg VERSION=$(git rev-parse --short HEAD) \
            -t snake-frontend:$(git rev-parse --short HEAD) \
            -t snake-frontend:latest \
            .
          container="$(docker create snake-frontend:latest)"
          docker cp "$container:/usr/src/app/static" dist

      - name: Clear azure storage container
        run: az storage blob delete-batch --account-name 'visnake' --source '$web' --auth-mode 'login'

      - name: Upload to azure storage
        run: az storage blob upload-batch --account-name 'visnake' --destination '$web' --source 'dist' --auth-mode 'login'

      - name: Purge CDN
        run: az cdn endpoint purge --content-paths '/*' --name visnake --profile-name visnake --resource-group visnake
