name: wasm_app

on:
  push:
    branches: [master]
    paths-ignore:
      - highscore-api/**
      - README.md
  pull_request:
    branches: [master]
    paths-ignore:
      - highscore-api/**
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.2.0

      - name: Cargo test
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          toolchain: stable

      - name: Wasm test
        run: wasm-pack test --headless --chrome

  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.5
        with:
          toolchain: stable
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - uses: jetli/wasm-pack-action@v0.2.0

      - name: Install javascript dependencies
        run: npm install

      - name: Build
        run: npm run build

  build-and-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.5
        with:
          toolchain: stable
      - uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - uses: jetli/wasm-pack-action@v0.2.0
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install javascript dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Clear azure storage container
        run: az storage blob delete-batch --account-name 'visnake' --source '$web' --auth-mode 'login'

      - name: Upload to azure storage
        run: az storage blob upload-batch --account-name 'visnake' --destination '$web' --source 'dist' --auth-mode 'login'
