name: wasm_app

on:
  push:
    branches: [master]
    paths:
      - front-end/**
      - .github/workflows/wasm_app.yml
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [master]
    paths:
      - front-end/**
      - .github/workflows/wasm_app.yml

defaults:
  run:
    working-directory: front-end

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Cargo test
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          toolchain: stable
          args: --manifest-path front-end/Cargo.toml

      - name: Wasm test
        run: wasm-pack test --headless --chrome

  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-20.04
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2

      - name: Docker build
        run: |
          docker build \
            --build-arg VERSION=$(git rev-parse --short HEAD) \
            -t snake-frontend:$(git rev-parse --short HEAD) \
            -t snake-frontend:latest \
            .
        env:
          DOCKER_BUILDKIT: "1"
      - name: Extract files to deploy
        run: |
          container="$(docker create snake-frontend:latest)"
          docker cp "$container:/usr/share/nginx/html" out

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_ISLAND_0A8DCC303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: front-end/out
          api_location: "" # leave blank or bring-your-own functions
          output_location: ""
          skip_app_build: true

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-20.04
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_ISLAND_0A8DCC303 }}
          action: close
